title: Pravata Lab
description: Pravata Lab - Uncovering the molecular logic of neurodevelopment through Post-Translational Modifications
baseurl: ""
url: "http://localhost:4000"

exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - .gitignore
  - README.md
  - start.sh
  - .git
